[build]
  publish = "."
[build.processing]
  skip_processing = false
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true
[context.production]
  command = ""
[context.deploy-preview]
  command = ""
[[context.deploy-preview.headers]]
  for = "/*"
  [context.deploy-preview.headers.values]
    X-Robots-Tag = "noindex"
[[context.branch-deploy.headers]]
  for = "/*"
  [context.branch-deploy.headers.values]
    X-Robots-Tag = "noindex"
[[redirects]]
  from   = "/*"
  to     = "/404.html"
  status = 404
